---
title: "Practice"
author: "Robin Elahi"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro to R

```{r}
source("http://www.openintro.org/stat/data/arbuthnot.R")

arbuthnot

dim(arbuthnot)

names(arbuthnot)

arbuthnot$boys
arbuthnot$girls

plot(x = arbuthnot$year, y = arbuthnot$girls)
with(arbuthnot, plot(girls ~ year))
plot(girls ~ year, data = arbuthnot)
plot(x = arbuthnot$year, y = arbuthnot$girls, type = "l")

?plot

5218 + 4683

arbuthnot$boys + arbuthnot$girls

# Create new vector
abg <- arbuthnot$boys + arbuthnot$girls


plot(arbuthnot$year, abg, type = "l")


5218 / 4683
5218 / (5218 + 4683)

arbuthnot$boys / (abg)

b_prop <- arbuthnot$boys / (abg)

plot(arbuthnot$year, b_prop, type = "l")

arbuthnot$boys > arbuthnot$girls



```

## Mean, variance, sd

## Boxplot exercise

```{r}

set.seed(101)
d <- rnorm(n = 15, mean = 80, sd = 20)
d <- round(d)
d

boxplot(d)

d <- c(d, 158, 141)

boxplot(d)


```

What is a median?

```{r}
d <- sort(d, decreasing = FALSE)
d

n <- length(d)
n

i_median <- 0.5 * n
i_median
i_median <- ceiling(i_median)
i_median
size_median <- d[i_median]
size_median
median(d)
```

Challenge: use a similar approach to get the first quartile. 

```{r}

i_25 <- 0.25 * n
i_25
i_25 <- ceiling(i_25)
size_25 <- d[i_25]
size_25
```

```{r}
i_75 <- 0.75 * n
i_75
i_75 <- ceiling(i_75)
size_75 <- d[i_75]
size_75
```

IQR
```{r}
size_iqr <- size_75 - size_25
size_iqr

IQR(d)

quantile(d)
quantile(d, probs = seq(0, 1, by = 0.1))

iqr_1.5 <- size_iqr * 1.5
iqr_1.5

max_whisker <- size_75 + iqr_1.5
min_whisker <- size_25 - iqr_1.5

```

```{r}

dat <- data.frame(mussel_size = d)
dat

install.packages("tidyverse")
library(tidyverse)


dat %>%
  ggplot(data = ., mapping = aes(x = "dot", y = mussel_size)) + 
  geom_point()

ggplot(data = dat, mapping = aes(x = "dot", y = mussel_size)) + 
  geom_point() + 
  geom_boxplot(data = dat, mapping = aes(x = "box", y = mussel_size)) + 
  geom_hline(yintercept = max_whisker, color = "red", linetype = "dashed") + 
  geom_hline(yintercept = min_whisker, color = "red", linetype = "dashed")
  


```









## Class mussel data

```{r}
dat <- read.csv(file = "https://raw.githubusercontent.com/elahi/xdp/master/data/class_data_mussels.csv")

head(dat)

str(dat)

boxplot(size_mm ~ name, data = dat)

boxplot(size_mm ~ site, data = dat)

boxplot(size_mm ~ joined_yes_no, data = dat)

```


